application: ctf-mannequin-moments
version: alpha1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /css
  static_dir: static/css/
  secure: always
- url: /js
  static_dir: static/js/
  secure: always
- url: /img
  static_dir: static/img/
  secure: always
- url: /setup
  script: setup.app
  login: admin
  secure: always
- url: /.*
  script: main.app
  secure: always
